### ISSUE TITLE
[FEATURE] - Create Become a Partner view

### ISSUE THREAD

**Issue by tariktuzlakovic** [croatiangrn/neural_web#3]

**Comment by tariktuzlakovic** [comment]
@croatiangrn gotov become a partner

**Comment by croatiangrn** [comment]
@tariktuzlakovic Zahvaljuje draga majka i obitelj

**Comment by croatiangrn** [comment]
@tariktuzlakovic Pogledaj formu, u tvojoj imaju obrubi, placeholderi nisu odmaknuti od lijeve strane. Sitnice al eto :D

**Comment by tariktuzlakovic** [comment]
@croatiangrn Kk, budem rijesil
